spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  cache:
    type: redis

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


  mvc:
    async:
      request-timeout: 600000






resend:
  api-key: ${RESEND_API_KEY}




jwt:
  key: ${JWT_KEY}

server:
  port: 5050
  tomcat:
    connection-timeout: 600000


cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}


google:
  client-id: ${GOOGLE_CLIENT-ID}
  client-secret: ${GOOGLE_CLIENT-SECRET}
  redirect-uri: https://nixora-image-latest.onrender.com/api/google/callback

  cloud:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    location: ${GOOGLE_CLOUD_LOCATION}
    documentai:
      processor-id: ${GOOGLE_CLOUD_DOCUMENTAI_PROCESSOR_ID}
    storage:
      bucket-name: ${GOOGLE_CLOUD_STORAGE_BUCKET_NAME}



trello:
  api-key: ${TRELLO_KEY}
  token: ${TRELLO_TOKEN}
  base-url: https://api.trello.com/1




logging:
  level:
    root: INFO
    com.nixora: DEBUG





